### ISSUE TITLE
Move naming to pulsar namespace

### ISSUE THREAD

**Issue by m1ga** [tidev/pulsar-titanium#654]
move the internal naming parts from atom to pulsar and make everything else pulsar ready

**Comment by ewanharris** [comment]
I've [took a start ](https://github.com/ewanharris/atom-appcelerator-titanium/tree/ci/pulsar-action)at trying to move over to the [official action](https://github.com/pulsar-edit/action-pulsar-dependency/actions/runs/4140791178/jobs/7159782904) but it currently seems to have issues.

I think the following are probably what should be aimed for to consider this done:

* Repo renamed
* Testing in CI working again
* Manual publish documented

Ideally we'd also get CI publish setup but we'll see how it goes

**Comment by cb1kenobi** [comment]
I can rename the repo. What do you want it called?

**Comment by ewanharris** [comment]
I think just `pulsar-titanium` should be good, so we can drop the `appcelerator` as part of this

**Comment by cb1kenobi** [comment]
This repo has been successfully renamed. I also updated the repo description.

**Comment by ewanharris** [comment]
FWIW, because of the botched attempt I made at renaming this package back when Atom was still a thing (and the registry was being DOS'd) I'm planning to follow [these steps](https://pulsar-edit.dev/docs/launch-manual/sections/behind-pulsar/#rename-your-package) to do it right so that we should hopefully switch with no hiccups

**Comment by m1ga** [comment]
@ewanharris can you unpublish the old appc package?
https://web.pulsar-edit.dev/packages/search?q=titanium still shows both and the old one is ranked higher. Don't think it should be there. `pulsar -p unpublish` according to the support, otherwise an issue in https://github.com/pulsar-edit/package-backend/issues and they'll do it.

**Comment by ewanharris** [comment]
@m1ga sure! Lemme try and get that unpublished!

**Comment by m1ga** [comment]
Think I can close this now! Old package is gone now :+1:
